set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(CMAKE_C_COMPILER gcc-15)
set(CMAKE_CXX_COMPILER g++-15)
set(CMAKE_OSX_DEPLOYMENT_TARGET 16.4 CACHE STRING "OSX deployment target")
set(CMAKE_OSX_ARCHITECTURES x86_64 CACHE STRING "OSX target architectures")

set(CMAKE_C_STANDARD 17)
set(CMAKE_CXX_STANDARD 20)

set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
